-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS autoinspection.cars
(
    vin character varying(17) COLLATE pg_catalog."default" NOT NULL,
    brand character varying(50) COLLATE pg_catalog."default",
    model character varying(50) COLLATE pg_catalog."default",
    year integer,
    color character varying(30) COLLATE pg_catalog."default",
    license_plate character varying(10) COLLATE pg_catalog."default",
    owner_id integer,
    CONSTRAINT cars_pkey PRIMARY KEY (vin),
    CONSTRAINT cars_license_plate_key UNIQUE (license_plate)
);

CREATE TABLE IF NOT EXISTS autoinspection.employment
(
    service_center_license character varying(10) COLLATE pg_catalog."default" NOT NULL,
    service_employee_id integer NOT NULL,
    CONSTRAINT employment_pkey PRIMARY KEY (service_center_license, service_employee_id)
);

CREATE TABLE IF NOT EXISTS autoinspection.inspections
(
    inspection_date date NOT NULL,
    result character varying(100) COLLATE pg_catalog."default",
    notes character varying(255) COLLATE pg_catalog."default",
    vin character varying(17) COLLATE pg_catalog."default",
    service_employee_id integer,
    CONSTRAINT inspections_pkey PRIMARY KEY (inspection_date)
);

CREATE TABLE IF NOT EXISTS autoinspection.logs
(
    log_id serial NOT NULL,
    table_name character varying COLLATE pg_catalog."default" NOT NULL,
    action_type character varying COLLATE pg_catalog."default" NOT NULL,
    action_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT logs_pkey PRIMARY KEY (log_id)
);

CREATE TABLE IF NOT EXISTS autoinspection.owners
(
    owner_id serial NOT NULL,
    full_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    address character varying(150) COLLATE pg_catalog."default",
    phone_number character varying(15) COLLATE pg_catalog."default",
    birth_date date,
    driver_license_number character varying(10) COLLATE pg_catalog."default",
    CONSTRAINT owners_pkey PRIMARY KEY (owner_id)
);

CREATE TABLE IF NOT EXISTS autoinspection.protocols
(
    protocol_number serial NOT NULL,
    issue_date date,
    violation_type character varying(100) COLLATE pg_catalog."default",
    fine_amount integer,
    vin character varying(17) COLLATE pg_catalog."default",
    officer_id integer,
    CONSTRAINT protocols_pkey PRIMARY KEY (protocol_number)
);

CREATE TABLE IF NOT EXISTS autoinspection.servicecenters
(
    license character varying(10) COLLATE pg_catalog."default" NOT NULL,
    name character varying(100) COLLATE pg_catalog."default",
    address character varying(150) COLLATE pg_catalog."default",
    contact_person character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT servicecenters_pkey PRIMARY KEY (license)
);

CREATE TABLE IF NOT EXISTS autoinspection.serviceemployees
(
    employee_id serial NOT NULL,
    full_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "position" character varying(50) COLLATE pg_catalog."default",
    contact_details character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT serviceemployees_pkey PRIMARY KEY (employee_id)
);

CREATE TABLE IF NOT EXISTS autoinspection.trafficofficers
(
    officer_id serial NOT NULL,
    full_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "position" character varying(50) COLLATE pg_catalog."default",
    department character varying(50) COLLATE pg_catalog."default",
    contact_details character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT trafficofficers_pkey PRIMARY KEY (officer_id)
);

ALTER TABLE IF EXISTS autoinspection.cars
    ADD CONSTRAINT cars_owner_id_fkey FOREIGN KEY (owner_id)
    REFERENCES autoinspection.owners (owner_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS autoinspection.employment
    ADD CONSTRAINT employment_service_center_license_fkey FOREIGN KEY (service_center_license)
    REFERENCES autoinspection.servicecenters (license) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS autoinspection.employment
    ADD CONSTRAINT employment_service_employee_id_fkey FOREIGN KEY (service_employee_id)
    REFERENCES autoinspection.serviceemployees (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS autoinspection.inspections
    ADD CONSTRAINT inspections_service_employee_id_fkey FOREIGN KEY (service_employee_id)
    REFERENCES autoinspection.serviceemployees (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS autoinspection.inspections
    ADD CONSTRAINT inspections_vin_fkey FOREIGN KEY (vin)
    REFERENCES autoinspection.cars (vin) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS autoinspection.protocols
    ADD CONSTRAINT protocols_officer_id_fkey FOREIGN KEY (officer_id)
    REFERENCES autoinspection.trafficofficers (officer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS autoinspection.protocols
    ADD CONSTRAINT protocols_vin_fkey FOREIGN KEY (vin)
    REFERENCES autoinspection.cars (vin) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;